name: Test versions


on: 
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
    branches:
      - 'main'

jobs:
  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} version
    steps:
      - name: Checkout

        uses: actions/checkout@v2
      - name: Set up python

        uses: actions/setup-python@v2.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Test app
        run: poetry run invoke test

        